version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: faheem-app:latest
    container_name: faheem-app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    environment:
      APP_NAME: ${APP_NAME:-Faheem}
      APP_VERSION: ${APP_VERSION:-0.1}
      POSTGRES_USERNAME: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-0000}
      POSTGRES_HOST: pgvector
      POSTGRES_PORT: 5432
      POSTGRES_MAIN_DATABASE: ${POSTGRES_DB:-minirag}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    depends_on:
      - pgvector
      - mongodb
    networks:
      - backend
    restart: unless-stopped

  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - "${MONGO_PORT:-27007}:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  pgvector:
    image: pgvector/pgvector:0.8.2-pg18
    container_name: pgvector
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-0000}
      POSTGRES_DB: ${POSTGRES_DB:-minirag}
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  backend:
    driver: bridge

volumes:
  mongodata: 
  pgvector_data: