"""create_bylaw_chunks_table

Revision ID: 5e4f9fee933c
Revises: b3fa572c3aff
Create Date: 2026-06-27 04:50:23.914950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e4f9fee933c'
down_revision: Union[str, Sequence[str], None] = 'b3fa572c3aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TABLE IF NOT EXISTS bylaw_chunks (
            chunk_id BIGSERIAL PRIMARY KEY,
            chunk_uuid UUID NOT NULL UNIQUE,
            text TEXT NOT NULL,
            metadata JSONB NOT NULL,
            chunk_order INTEGER NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
        )
    """)
    op.execute("DROP INDEX IF EXISTS kb_is211_vector_idx")
    op.execute("DROP TABLE IF EXISTS kb_is211 CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_is211',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('kb_is211_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kb_is211_pkey'))
    )
    op.create_index(op.f('kb_is211_vector_idx'), 'kb_is211', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('bylaw_chunks')
    # ### end Alembic commands ###
