"""create_bylaw_chunks_table

Revision ID: b3fa572c3aff
Revises: 0a9157642013
Create Date: 2026-06-27 04:25:37.558541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3fa572c3aff'
down_revision: Union[str, Sequence[str], None] = '0a9157642013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_bylaw_documents_bylaw_id")
    op.execute("DROP TABLE IF EXISTS bylaw_documents CASCADE")
    op.execute("DROP TABLE IF EXISTS kb_ma214 CASCADE")
    op.execute("DROP INDEX IF EXISTS kb_hu112_vector_idx")
    op.execute("DROP TABLE IF EXISTS kb_hu112 CASCADE")
    op.execute("DROP INDEX IF EXISTS kb_is211_vector_idx")
    op.execute("DROP TABLE IF EXISTS kb_is211 CASCADE")
    op.execute("DROP TABLE IF EXISTS kb_ma111 CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_ma111',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('kb_ma111_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kb_ma111_pkey'))
    )
    op.create_table('kb_is211',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('kb_is211_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kb_is211_pkey'))
    )
    op.create_index(op.f('kb_is211_vector_idx'), 'kb_is211', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('kb_hu112',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('kb_hu112_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kb_hu112_pkey'))
    )
    op.create_index(op.f('kb_hu112_vector_idx'), 'kb_hu112', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('kb_ma214',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('kb_ma214_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kb_ma214_pkey'))
    )
    op.create_table('bylaw_documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(), server_default=sa.text("'bylaw'::character varying"), autoincrement=False, nullable=True),
    sa.Column('bylaw_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('program', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('specialization', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bylaw_documents_pkey'))
    )
    op.create_index(op.f('idx_bylaw_documents_bylaw_id'), 'bylaw_documents', ['bylaw_id'], unique=False)
    op.drop_table('bylaw_chunks')
    # ### end Alembic commands ###
